#!groovy

def BACKEND_DIR = 'Backend/microblog-backend'

pipeline {
    agent {
        docker {
            image 'maven:3-alphine'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm;
            }
        }

        stage('Test') {
            steps {
                dir(BACKEND_DIR) {
                    sh 'mvn test'
                }
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
    }
}