#!groovy

def BACKEND_DIR = 'Backend/microblog-backend'

pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                checkout scm;
            }
        }

        stage('Test') {
            steps {
                dir(BACKEND_DIR) {
                    sh 'mvn test'
                }
            }
        }
    }
}